### ISSUE TITLE
Create a homepage

### ISSUE THREAD

**Issue by nicordev** [nicordev/formation-oc-php-projet5-blog#26]
This page will show some posts grouped by categories.
This issue requires a tag and a category management system.

**Comment by SansGodasse** [comment]
This page will show some posts grouped by categories.

**Comment by nicordev** [comment]
Closed by [this pull request](https://github.com/nicordev/formation-oc-php-projet5-blog/commit/f69bbf2d0bd56d9d6fb28369159369a28a008b93)
